In [82]:
import gym
import torch
import numpy as np

In [92]:
env = gym.make('CartPole-v0')
env.spec.thre

AttributeError: 'EnvSpec' object has no attribute 'end'

In [40]:
env.reset()
state = env.step(env.action_space.sample())[0]
print(torch.from_numpy(state).float().unsqueeze(0).shape)

torch.Size([1, 4])


In [48]:
t = torch.Tensor([[0.23, 0.77]])
t.size()

torch.Size([1, 2])

tensor([[-1.4697, -0.2614]])


In [78]:
m = torch.distributions.categorical.Categorical(t)
action = m.sample()
print(action)
print(m.log_prob(action))

tensor([1])
tensor([-0.2614])


In [74]:
c0 = 0
c1 = 0
for i in range (1000000):
    a = m.sample().item()
    if a == 0:
        c0 += 1
    else:
        c1 += 1
print(c0/(c0+c1))


0.230098
